### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jrschumacher** [cht8687/react-text-collapse#2]
https://github.com/cht8687/react-text-collapse/blob/e2edfadf4643c61d75e1305fb4d50f04573c8aea/dist/index.js#L7

**Comment by jorisw** [comment]
Same here, when using `import`:

````
10:17:29 AM web.1 |  ERROR in ./~/react-text-collapse/dist/index.js
10:17:29 AM web.1 |  Module not found: Error: Can't resolve './ReactTextCollapse' in 'app/node_modules/react-text-collapse/dist'
10:17:29 AM web.1 |   @ ./~/react-text-collapse/dist/index.js 7:25-55
```

What's with the use of `~` anyway?

**Comment by cht8687** [comment]
Hi @jorisw @jrschumacher , I published a new version. try it out.
if it doesn't work, try install react-motion separately.
I test it in my [https://github.com/cht8687/test-project](url), seems working fine for me.
