### ISSUE TITLE
Deprecated Dependencies

### ISSUE THREAD

**Issue by Sauerbrei** [cht8687/react-text-collapse#4]
I am using version ^0.4.3 and every time I am building my react app with docker and yarn the following deprecation warnings occur:

`warning react-text-collapse > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`

`warning react-text-collapse > gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`

`warning react-text-collapse > gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`

`warning react-text-collapse > gulp > vinyl-fs > graceful-fs > natives@1.1.2: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.`

`warning react-text-collapse > gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

`warning react-text-collapse > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

`warning react-text-collapse > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js`

`warning react-text-collapse > gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

`warning react-text-collapse > gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

It would be great if you could update the dependencies :)

**Comment by cht8687** [comment]
@Sauerbrei 

Could you try the latest version 0.5.0? Let me know if it still has those warnings.

**Comment by Sauerbrei** [comment]
@cht8687 

thank you for the quick response. this issue is fixed :)

**Comment by cht8687** [comment]
@Sauerbrei  :+1:
