### ISSUE TITLE
Module not found: Error: Can't resolve 'react-motion'

### ISSUE THREAD

**Issue by jbojcic1** [cht8687/react-text-collapse#5]
I am getting `Module not found: Error: Can't resolve 'react-motion'` when I add your package

**Comment by cht8687** [comment]
@jbojcic1 
You need to install react-motion as peerDependencies.
Let me know if you have any other issues.

**Comment by rainshang** [comment]
`+ react-motion@0.5.2
updated 1 package in 17.322s`
`+ react-text-collapse@0.5.0
updated 1 package in 16.952s`
It is still showing `./node_modules/react-text-collapse/dist/ReactTextCollapse.js
Module not found: Can't resolve 'react-motion' in ...`
